services:
  db:
    image: postgres:15.4-alpine
    container_name: weather-db
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - db_main:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-api
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    env_file:
      - ./.env
    ports:
      - '3000:3000'

volumes:
  db_main:
