services:
  db:
    image: postgres:15.4-alpine
    container_name: weather-db
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - db_main:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: weather-redis
    restart: always
    ports:
      - '6379:6379'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-api
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    env_file:
      - ./.env
    ports:
      - '3000:3000'

volumes:
  db_main:
